[PR #8403/572caeaa backport][stable-8] keycloak_client: avoid TypeError if `result["attributes"]` is a list (#8426)
keycloak_client: avoid TypeError if `result["attributes"]` is a list (#8403)

* fix(keycloak_client): avoid TypeError if attributes is a list

As sanitize_cr might be executed after normalise_cr, result['attributes'] can be of type list and we
run into:

TypeError: list indices must be integers or slices, not str

* Update changelog fragment.

---------

Co-authored-by: Felix Fontein <felix@fontein.de>
(cherry picked from commit 572caeaa39ad3efd6083afafba9fd4fe4c88f9fd)

Co-authored-by: Thomas Bach <63091663+thomasbach-dev@users.noreply.github.com>