openbsd_pkg: Fix regexp matching crash (#3161) (#3186)
When a package name contains special characters (e.g. "g++"), they are
interpreted as part of the regexp.

This can lead to a crash with an error in the python re module, for
instance with "g++":

    sre_constants.error: multiple repeat

Fix this by escaping the package name.

Co-authored-by: Baptiste Jonglez <git@bitsofnetworks.org>
(cherry picked from commit 56b5be0630e226f20cf461b2ab9c722de5e34483)

Co-authored-by: zorun <github@bitsofnetworks.org>